/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_stationweb_free: (a: number, b: number) => void;
export const stationweb_activate: (a: number, b: number, c: number) => number;
export const stationweb_close_transcript: (a: number) => void;
export const stationweb_composer_state: (a: number) => [number, number];
export const stationweb_debug_json: (a: number) => [number, number];
export const stationweb_debug_state: (a: number) => [number, number];
export const stationweb_focus_on: (a: number, b: number, c: number) => void;
export const stationweb_hotspot_rects: (a: number) => [number, number];
export const stationweb_new: (a: any, b: any) => [number, number, number];
export const stationweb_register_display_source: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: any) => void;
export const stationweb_resize: (a: number) => void;
export const stationweb_select_by_id: (a: number, b: number, c: number) => void;
export const stationweb_set_action_callback: (a: number, b: any) => void;
export const stationweb_set_active: (a: number, b: number) => void;
export const stationweb_set_composer: (a: number, b: number, c: number, d: number) => void;
export const stationweb_set_layout: (a: number, b: number, c: number) => void;
export const stationweb_set_transcript: (a: number, b: any) => [number, number, number];
export const stationweb_set_visuals: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const stationweb_unregister_display_source: (a: number, b: number, c: number) => void;
export const stationweb_update_snapshot: (a: number, b: any) => [number, number];
export const wasm_bindgen__closure__destroy__h0b7c3dde0a11a997: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hccf83c1ad0c1d3f3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3378a55d603b975f: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6044e1f38f492cc6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h63b5eb8c1813e0ac: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9d0506930843bd3e: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
