/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_stationweb_free: (a: number, b: number) => void;
export const stationweb_activate: (a: number, b: number, c: number) => number;
export const stationweb_close_transcript: (a: number) => void;
export const stationweb_composer_state: (a: number) => [number, number];
export const stationweb_debug_json: (a: number) => [number, number];
export const stationweb_debug_lose_gpu: (a: number) => number;
export const stationweb_debug_state: (a: number) => [number, number];
export const stationweb_focus_on: (a: number, b: number, c: number) => void;
export const stationweb_hotspot_rects: (a: number) => [number, number];
export const stationweb_new: (a: any, b: any) => [number, number, number];
export const stationweb_register_display_source: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: any) => void;
export const stationweb_resize: (a: number) => void;
export const stationweb_select_by_id: (a: number, b: number, c: number) => void;
export const stationweb_set_action_callback: (a: number, b: any) => void;
export const stationweb_set_active: (a: number, b: number) => void;
export const stationweb_set_composer: (a: number, b: number, c: number, d: number) => void;
export const stationweb_set_layout: (a: number, b: number, c: number) => void;
export const stationweb_set_transcript: (a: number, b: any) => [number, number, number];
export const stationweb_set_visuals: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const stationweb_unregister_display_source: (a: number, b: number, c: number) => void;
export const stationweb_update_snapshot: (a: number, b: any) => [number, number];
export const wasm_bindgen__closure__destroy__h829070727a6c9b28: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__he88d688485a742c0: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hb9ef122cd6bafce1: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a33e0948713da17: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hdef3f4e3a527b0f6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hca5f75ff963c78a9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7dfd20110b18ff44: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h18ce2992322c96bf: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
