#!/usr/bin/env bash
#
# update-vortex-pkg.sh — Rebuild VortexGuestTools.pkg from a Vortex source
# tree and refresh both the vendored pkg and its integrity manifest atomically.
#
# Usage:
#   scripts/update-vortex-pkg.sh                       # Use $VORTEX_SRC or ~/projects/vortex
#   scripts/update-vortex-pkg.sh /path/to/vortex       # Explicit path
#   scripts/update-vortex-pkg.sh --allow-dirty         # Skip the clean-tree check
#
# Why: the pkg in vendor/vortex-guest-tools/ is a binary blob with no link
# back to its source commit. This script is the only sanctioned way to
# refresh it — it records the exact source commit, rebuilds from a known
# state, and rewrites the manifest so setup-macos.sh's integrity check
# keeps passing.

set -euo pipefail

die()  { echo "error: $*" >&2; exit 1; }
info() { echo ":: $*"; }
ok()   { echo "   ✓ $*"; }

# ── Args ────────────────────────────────────────────────────────────────────

VORTEX_SRC=""
ALLOW_DIRTY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --allow-dirty) ALLOW_DIRTY=true; shift ;;
        -h|--help) sed -n '3,15p' "$0" | sed 's/^# \?//'; exit 0 ;;
        --*) die "unknown option: $1" ;;
        *) VORTEX_SRC="$1"; shift ;;
    esac
done

[[ -z "$VORTEX_SRC" ]] && VORTEX_SRC="${VORTEX_SRC:-${HOME}/projects/vortex}"
[[ -d "$VORTEX_SRC" ]] || die "Vortex source not found at: $VORTEX_SRC"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INTENDANT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENDOR_DIR="$INTENDANT_ROOT/vendor/vortex-guest-tools"
PKG_DST="$VENDOR_DIR/VortexGuestTools.pkg"
MANIFEST="$VENDOR_DIR/VortexGuestTools.pkg.manifest"

# ── Source-tree state ───────────────────────────────────────────────────────

info "Vortex source: $VORTEX_SRC"

VORTEX_SHA="$(git -C "$VORTEX_SRC" rev-parse HEAD)"
VORTEX_SHORT="$(git -C "$VORTEX_SRC" rev-parse --short HEAD)"
info "Vortex HEAD: $VORTEX_SHORT"

if ! $ALLOW_DIRTY && [[ -n "$(git -C "$VORTEX_SRC" status --porcelain)" ]]; then
    die "Vortex source tree is dirty. Commit your changes or pass --allow-dirty."
fi
DIRTY=false
[[ -n "$(git -C "$VORTEX_SRC" status --porcelain)" ]] && DIRTY=true

# ── Build ───────────────────────────────────────────────────────────────────

info "Building pkg via $VORTEX_SRC/GuestTools/build-pkg.sh..."
bash "$VORTEX_SRC/GuestTools/build-pkg.sh"

BUILT_PKG="$VORTEX_SRC/GuestTools/build/VortexGuestTools.pkg"
[[ -f "$BUILT_PKG" ]] || die "Build did not produce $BUILT_PKG"

# ── Extract + hash ──────────────────────────────────────────────────────────

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

info "Computing hashes..."
PKG_SHA="$(shasum -a 256 "$BUILT_PKG" | awk '{print $1}')"

(
    cd "$WORK"
    xar -xf "$BUILT_PKG"
    mkdir extracted
    (cd extracted && cat ../Payload | gunzip -dc | cpio -i 2>/dev/null)
)

DAEMON_SHA="$(shasum -a 256 "$WORK/extracted/usr/local/bin/VortexAudioDaemon" | awk '{print $1}')"
PLUGIN_SHA="$(shasum -a 256 "$WORK/extracted/Library/Audio/Plug-Ins/HAL/VortexAudioPlugin.driver/Contents/MacOS/VortexAudioPlugin" | awk '{print $1}')"
PKG_INTERNAL_VERSION="$(tr -d '[:space:]' < "$WORK/extracted/usr/local/share/vortex/VERSION" 2>/dev/null || echo "unknown")"

# ── Install into vendor/ ────────────────────────────────────────────────────

cp "$BUILT_PKG" "$PKG_DST"
ok "vendor pkg refreshed: $PKG_DST"

# ── Write manifest ──────────────────────────────────────────────────────────

# A dirty source tree means the commit alone doesn't uniquely identify the
# build — mark the source commit unverified so the manifest is honest about
# the gap.
VERIFIED=true
if $DIRTY; then
    VERIFIED=false
fi

cat > "$MANIFEST" <<EOF
# Vortex Guest Tools pkg integrity manifest.
#
# Verified by scripts/setup-macos.sh before invoking \`installer -pkg\`.
# Regenerated by scripts/update-vortex-pkg.sh from ~/projects/vortex.
#
# Format: simple \`key: value\` lines. Comments start with \`#\`.

pkg_sha256: $PKG_SHA
pkg_internal_version: $PKG_INTERNAL_VERSION

# Hashes of the binaries inside the pkg payload — informational, but useful
# for diagnosing partial-corruption cases where \`pkg_sha256\` alone wouldn't
# tell you which file changed.
daemon_sha256: $DAEMON_SHA
plugin_sha256: $PLUGIN_SHA

# Vortex source commit that produced this pkg.
#
# Note: the bundled Mach-O binaries are ad-hoc (linker-only) signed, so
# byte-exact rebuild reproducibility is not guaranteed even from the same
# commit. The pkg_sha256 check is the authoritative integrity gate.
vortex_source_commit: $VORTEX_SHA
vortex_source_commit_verified: $VERIFIED
EOF

ok "manifest refreshed: $MANIFEST"

echo ""
info "Summary:"
echo "   vortex commit:  $VORTEX_SHORT$($DIRTY && echo ' (dirty)')"
echo "   pkg sha256:     $PKG_SHA"
echo "   pkg version:    $PKG_INTERNAL_VERSION"
echo ""
info "Review the diff, then commit vendor/vortex-guest-tools/."
