#!/usr/bin/env bash
# Regenerate the vendored CodeMirror bundle served by the dashboard editor
# (Files tab). Downloads a pinned CodeMirror 5 release from unpkg and
# concatenates the core, the addons, and the language modes the editor
# ships into two self-contained assets:
#
#   static/codemirror-bundle.js
#   static/codemirror-bundle.css
#
# CodeMirror 5 is MIT-licensed and ships prebuilt (no npm/rollup step), which
# is what makes a byte-auditable vendored bundle practical. To upgrade: bump
# CODEMIRROR_VERSION, rerun, review the diff, rebuild.
set -euo pipefail

CODEMIRROR_VERSION="5.65.19"
BASE_URL="https://unpkg.com/codemirror@${CODEMIRROR_VERSION}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_JS="${REPO_ROOT}/static/codemirror-bundle.js"
OUT_CSS="${REPO_ROOT}/static/codemirror-bundle.css"

# Order matters: the core first; addon/mode/simple before the modes that
# build on it (dockerfile); xml/javascript/css before htmlmixed, which
# delegates to them.
JS_PARTS=(
  lib/codemirror.js
  addon/mode/simple.js
  addon/edit/matchbrackets.js
  addon/edit/closebrackets.js
  addon/selection/active-line.js
  addon/search/searchcursor.js
  addon/comment/comment.js
  mode/meta.js
  mode/clike/clike.js
  mode/css/css.js
  mode/javascript/javascript.js
  mode/xml/xml.js
  mode/htmlmixed/htmlmixed.js
  mode/markdown/markdown.js
  mode/python/python.js
  mode/rust/rust.js
  mode/go/go.js
  mode/shell/shell.js
  mode/sql/sql.js
  mode/swift/swift.js
  mode/toml/toml.js
  mode/yaml/yaml.js
  mode/diff/diff.js
  mode/dockerfile/dockerfile.js
  mode/powershell/powershell.js
)

CSS_PARTS=(
  lib/codemirror.css
)

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

fetch() {
  local rel="$1" out="$2"
  echo "  ${rel}"
  curl -fsSL --retry 3 --max-time 60 "${BASE_URL}/${rel}" -o "${out}"
}

echo "Fetching CodeMirror ${CODEMIRROR_VERSION} from unpkg…"
fetch LICENSE "${WORKDIR}/LICENSE"

header() {
  local kind="$1"
  cat <<EOF
/*!
 * Vendored CodeMirror ${CODEMIRROR_VERSION} ${kind} bundle for the Intendant
 * dashboard editor. Generated by scripts/vendor-codemirror.sh — do not edit
 * by hand; bump the version in that script and rerun it instead.
 *
 * Upstream: https://codemirror.net/5/ (MIT license, reproduced below).
 *
$(sed 's/^/ * /' "${WORKDIR}/LICENSE")
 */
EOF
}

{
  header "JS"
  for part in "${JS_PARTS[@]}"; do
    fetch "${part}" "${WORKDIR}/part" >&2
    printf '\n/* --- codemirror@%s/%s --- */\n' "${CODEMIRROR_VERSION}" "${part}"
    cat "${WORKDIR}/part"
  done
} > "${OUT_JS}"

{
  header "CSS"
  for part in "${CSS_PARTS[@]}"; do
    fetch "${part}" "${WORKDIR}/part" >&2
    printf '\n/* --- codemirror@%s/%s --- */\n' "${CODEMIRROR_VERSION}" "${part}"
    cat "${WORKDIR}/part"
  done
} > "${OUT_CSS}"

echo "Wrote ${OUT_JS} ($(wc -c < "${OUT_JS}" | tr -d ' ') bytes)"
echo "Wrote ${OUT_CSS} ($(wc -c < "${OUT_CSS}" | tr -d ' ') bytes)"
