/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_xrweb_free: (a: number, b: number) => void;
export const xrweb_activate: (a: number, b: number, c: number) => number;
export const xrweb_debugJson: (a: number) => [number, number];
export const xrweb_enter: (a: number, b: number, c: number) => any;
export const xrweb_exit: (a: number) => void;
export const xrweb_markTerminalCanvasDirty: (a: number, b: number, c: number) => void;
export const xrweb_new: () => number;
export const xrweb_probeSupport: (a: number) => any;
export const xrweb_registerDisplaySource: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: any) => void;
export const xrweb_registerTerminalCanvas: (a: number, b: number, c: number, d: any) => void;
export const xrweb_setActionCallback: (a: number, b: any) => void;
export const xrweb_setOnSessionEnd: (a: number, b: any) => void;
export const xrweb_unregisterDisplaySource: (a: number, b: number, c: number) => void;
export const xrweb_unregisterTerminalCanvas: (a: number, b: number, c: number) => void;
export const xrweb_updateSnapshot: (a: number, b: any) => void;
export const xrweb_updateTerminal: (a: number, b: any) => void;
export const wasm_bindgen__closure__destroy__h95fa55e82713b162: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hb9ef122cd6bafce1: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h80d27238e69792d0: (a: number, b: number, c: number, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8830e5bad9fe7bb6: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5fa997591c1e8ef4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7dfd20110b18ff44: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
